spring:
  thymeleaf:
    cache: false
    #非严格模式的HTML语法检查
    mode: LEGACYHTML5
  aop:
    proxy-target-class: true
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
  cache:
    ehcache:
      config: ehcache/ehcache.xml
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/templateItemsOauth2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: 547521014
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: sso-auth-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
    pool:
      max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123654@localhost:8080/eureka/
feign:
  httpclient:
    connection-timeout: 10000