eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka/
server:
  port: 8082
spring:
  application:
    name: sso-zuul
zuul:
  routes:
    oauth2:
      path: /oauth2/**
      serviceId: sso-auth-server
    login:
      path: /login/**
      serviceId: sso-login